-- Pipply database setup for a new Supabase project.
-- Run this in the Supabase SQL Editor before starting the app.

DO $$
BEGIN
  CREATE TYPE public.application_status AS ENUM (
    'draft',
    'applied',
    'interviewing',
    'offer',
    'rejected',
    'withdrawn',
    'ghosted'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.location_type AS ENUM (
    'remote',
    'hybrid',
    'on_site'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.application_source_type AS ENUM (
    'manual',
    'email',
    'scrape'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.application_field_events_field_name AS ENUM (
    'compensation_amount',
    'salary_type',
    'salary_per_hour',
    'salary_yearly',
    'location_type',
    'location',
    'contact_person',
    'status',
    'date_applied',
    'notes'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  job_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.application_current (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL UNIQUE REFERENCES public.applications(id) ON DELETE CASCADE,
  company_name text NOT NULL DEFAULT 'Company',
  job_title text NOT NULL DEFAULT 'Job Title',
  compensation_amount numeric,
  salary_type text,
  salary_per_hour numeric,
  salary_yearly numeric,
  location_type public.location_type,
  location text,
  date_applied date NOT NULL DEFAULT current_date,
  contact_person text,
  status public.application_status NOT NULL DEFAULT 'applied',
  notes text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT application_current_compensation_amount_nonnegative
    CHECK (compensation_amount IS NULL OR compensation_amount >= 0),
  CONSTRAINT application_current_salary_type_valid
    CHECK (
      salary_type IS NULL
      OR salary_type IN ('hourly', 'weekly', 'biweekly', 'monthly', 'yearly')
    )
);

CREATE TABLE IF NOT EXISTS public.emails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider text,
  provider_message_id text,
  from_email text,
  subject text,
  body text,
  received_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_message_id)
);

CREATE TABLE IF NOT EXISTS public.application_email_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
  email_id bigint NOT NULL REFERENCES public.emails(id) ON DELETE CASCADE,
  source text NOT NULL DEFAULT 'api',
  confidence integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.application_field_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
  source_type public.application_source_type,
  email_id bigint REFERENCES public.emails(id) ON DELETE SET NULL,
  field_name public.application_field_events_field_name NOT NULL,
  value_text text,
  value_number numeric,
  value_date date,
  value_location_type public.location_type,
  value_status public.application_status,
  event_time timestamptz NOT NULL DEFAULT now(),
  confidence integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider text NOT NULL,
  access_token text NOT NULL,
  refresh_token text,
  expires_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, provider)
);

CREATE TABLE IF NOT EXISTS public.user_scan_preferences (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  auto_scan_enabled boolean NOT NULL DEFAULT false,
  scan_window_start date,
  last_scan_time timestamptz,
  preferred_scan_hour integer NOT NULL DEFAULT 8,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_scan_preferences_hour_valid
    CHECK (preferred_scan_hour BETWEEN 0 AND 23)
);

CREATE INDEX IF NOT EXISTS applications_user_id_idx
  ON public.applications(user_id);

CREATE INDEX IF NOT EXISTS application_current_application_id_idx
  ON public.application_current(application_id);

CREATE INDEX IF NOT EXISTS emails_user_id_idx
  ON public.emails(user_id);

CREATE INDEX IF NOT EXISTS emails_provider_message_id_idx
  ON public.emails(provider, provider_message_id);

CREATE INDEX IF NOT EXISTS application_email_links_application_id_idx
  ON public.application_email_links(application_id);

CREATE INDEX IF NOT EXISTS application_email_links_email_id_idx
  ON public.application_email_links(email_id);

CREATE INDEX IF NOT EXISTS application_field_events_application_id_idx
  ON public.application_field_events(application_id);

CREATE INDEX IF NOT EXISTS application_field_events_email_id_idx
  ON public.application_field_events(email_id);

CREATE INDEX IF NOT EXISTS user_tokens_user_provider_idx
  ON public.user_tokens(user_id, provider);
